// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFiHD5cEW_rpu9P6PYse49hjTK99diWw',
    appId: '1:978659962133:web:f12c534daa1d25f1b00d1c',
    messagingSenderId: '978659962133',
    projectId: 'chatappp-c0f1c',
    authDomain: 'chatappp-c0f1c.firebaseapp.com',
    storageBucket: 'chatappp-c0f1c.firebasestorage.app',
    measurementId: 'G-JWC6QS38B4',
    databaseURL: 'https://chatappp-c0f1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeaWlq6SgNs23AcbZtZxvdLM8Iewf7zxg',
    appId: '1:978659962133:android:5165af5bc5ad2c26b00d1c',
    messagingSenderId: '978659962133',
    projectId: 'chatappp-c0f1c',
    storageBucket: 'chatappp-c0f1c.firebasestorage.app',
    databaseURL: 'https://chatappp-c0f1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjpY4PMLB_T0ZHh1EpAKWLzXlpxbrfEY',
    appId: '1:978659962133:ios:1d0d21814dfd46d5b00d1c',
    messagingSenderId: '978659962133',
    projectId: 'chatappp-c0f1c',
    storageBucket: 'chatappp-c0f1c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
    databaseURL: 'https://chatappp-c0f1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZjpY4PMLB_T0ZHh1EpAKWLzXlpxbrfEY',
    appId: '1:978659962133:ios:1d0d21814dfd46d5b00d1c',
    messagingSenderId: '978659962133',
    projectId: 'chatappp-c0f1c',
    storageBucket: 'chatappp-c0f1c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
    databaseURL: 'https://chatappp-c0f1c-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANFiHD5cEW_rpu9P6PYse49hjTK99diWw',
    appId: '1:978659962133:web:9ec30c0862ae6412b00d1c',
    messagingSenderId: '978659962133',
    projectId: 'chatappp-c0f1c',
    authDomain: 'chatappp-c0f1c.firebaseapp.com',
    storageBucket: 'chatappp-c0f1c.firebasestorage.app',
    measurementId: 'G-SL4WM4DWBZ',
    databaseURL: 'https://chatappp-c0f1c-default-rtdb.firebaseio.com',
  );
}
